package fr.ambigovee.tv;

/**
 * Bilingual local phone page used for the one-time Philips pairing flow.
 *
 * No external CDN, font, script or image is used: the page is fully self-contained
 * and is served directly by the TV on the local network.
 */
final class PairingPhonePage {

    private PairingPhonePage() {}

    static String render() {
        return """
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<meta name="theme-color" content="#080b12">
<title>AmbiGovee — Philips pairing</title>
<style>
:root{color-scheme:dark;--bg:#070a10;--card:#121824;--line:#2a3449;--text:#f7f8fc;--muted:#98a3b5;--violet:#7658f4;--green:#6fe1a7;--yellow:#f2c96f;--red:#ff8ca0}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;padding:22px;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:radial-gradient(720px 420px at 10% 0%,rgba(111,76,255,.24),transparent 60%),radial-gradient(600px 500px at 100% 100%,rgba(97,44,140,.2),transparent 62%),var(--bg);display:flex;align-items:center;justify-content:center}
.shell{width:min(560px,100%)}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.brand{display:flex;gap:10px;align-items:center;font-weight:900}.brandMark{width:35px;height:35px;border-radius:12px;background:linear-gradient(135deg,#8f79ff,#6242dd);display:grid;place-items:center;box-shadow:0 8px 26px rgba(107,77,255,.35)}.lang{display:flex;background:#111722;border:1px solid var(--line);padding:3px;border-radius:12px}.lang button{border:0;background:transparent;color:#768195;padding:7px 10px;border-radius:9px;font-weight:850}.lang button.active{background:#2b2146;color:#eee9ff}
.card{position:relative;overflow:hidden;background:linear-gradient(145deg,rgba(20,27,40,.98),rgba(12,17,26,.98));border:1px solid var(--line);border-radius:28px;padding:27px;box-shadow:0 26px 78px rgba(0,0,0,.38)}.kicker{color:#aa9aff;font-size:11px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}h1{font-size:31px;line-height:1.08;letter-spacing:-.025em;margin:9px 0 10px}.sub{color:#a5afbf;font-size:15px;line-height:1.5;margin:0 0 20px}.steps{border-top:1px solid #242d3f}.step{display:flex;gap:13px;align-items:flex-start;padding:14px 0;border-bottom:1px solid #242d3f}.num{min-width:34px;height:34px;border-radius:12px;background:#34275c;color:#ded7ff;font-weight:900;display:grid;place-items:center}.stepText{padding-top:5px;color:#e0e5ee;font-size:14px;line-height:1.35}.hint{color:#7e899d;font-size:12px;margin-top:4px}
button.primary{width:100%;border:0;border-radius:17px;padding:16px 18px;margin-top:18px;color:white;background:linear-gradient(135deg,#6548df,#8e76ff);font-size:16px;font-weight:900;box-shadow:0 10px 30px rgba(101,72,223,.3)}button:disabled{opacity:.5}.pinWrap{display:none}.pinWrap.show{display:block}input{width:100%;border:1px solid #46536e;background:#0a0f18;color:#fff;border-radius:18px;padding:18px;font-size:30px;letter-spacing:.22em;text-align:center;outline:none}input:focus{border-color:#927dff;box-shadow:0 0 0 3px rgba(146,125,255,.15)}.timer{font-size:12px;color:#a89ae0;margin:10px 2px 0}.status{margin-top:16px;border:1px solid #2c374d;background:#0e151f;border-radius:16px;padding:13px 15px;color:#c2cad7;font-size:13px;line-height:1.42}.status.ok{border-color:#2a6a50;background:#10271d;color:#85e4b5}.status.warn{border-color:#74612f;background:#211c10;color:#f4d07c}.status.bad{border-color:#773949;background:#261319;color:#ff9dae}.privacy{margin-top:15px;text-align:center;color:#667285;font-size:11px;line-height:1.45}.success{display:none;text-align:center;padding:24px 4px 6px}.success.show{display:block}.check{width:86px;height:86px;border-radius:29px;margin:0 auto 18px;background:linear-gradient(135deg,#176844,#2e9d68);display:grid;place-items:center;font-size:44px;font-weight:900;box-shadow:0 18px 50px rgba(36,151,98,.3);animation:pop .35s ease-out}.success h1{font-size:32px}.success p{color:#a1acbd;line-height:1.55;margin:0}.spark{position:absolute;width:7px;height:7px;border-radius:99px;background:#987fff;opacity:0;pointer-events:none}.success.show~.spark{animation:spark 1.3s ease-out forwards}.s1{left:15%;top:18%}.s2{left:28%;top:9%;animation-delay:.08s!important}.s3{right:19%;top:14%;animation-delay:.16s!important}.s4{right:8%;top:28%;animation-delay:.24s!important}.s5{left:10%;top:40%;animation-delay:.3s!important}@keyframes pop{0%{transform:scale(.72);opacity:0}100%{transform:scale(1);opacity:1}}@keyframes spark{0%{opacity:0;transform:translateY(10px) scale(.3)}25%{opacity:1}100%{opacity:0;transform:translateY(-44px) scale(1.2)}}.hidden{display:none!important}@media(max-width:420px){body{padding:14px}.card{padding:22px}h1{font-size:27px}}
</style>
</head>
<body>
<main class="shell"><header class="top"><div class="brand"><div class="brandMark">🌈</div><div>AmbiGovee</div></div><div class="lang"><button id="enBtn">EN</button><button id="frBtn">FR</button></div></header>
<section class="card">
<div id="flow"><div class="kicker" data-i18n="kicker"></div><h1 id="title"></h1><p class="sub" id="subtitle"></p>
<div id="intro"><div class="steps">
<div class="step"><div class="num">1</div><div class="stepText"><b data-i18n="s1"></b><div class="hint" data-i18n="s1h"></div></div></div>
<div class="step"><div class="num">2</div><div class="stepText"><b data-i18n="s2"></b><div class="hint" data-i18n="s2h"></div></div></div>
<div class="step"><div class="num">3</div><div class="stepText"><b data-i18n="s3"></b><div class="hint" data-i18n="s3h"></div></div></div>
</div><button class="primary" id="start" type="button" data-i18n="start"></button></div>
<form id="pinForm" class="pinWrap"><input id="pin" name="pin" inputmode="numeric" pattern="[0-9]*" autocomplete="one-time-code" maxlength="8" placeholder="PIN"><div class="timer" id="timer"></div><button class="primary" id="send" type="submit" data-i18n="connect"></button></form>
<button class="primary hidden" id="retry" type="button" data-i18n="retry"></button><div id="status" class="status"></div><div class="privacy" data-i18n="privacy"></div></div>
<div class="success" id="success"><div class="check">✓</div><h1 data-i18n="successTitle"></h1><p data-i18n="successBody"></p></div>
<i class="spark s1"></i><i class="spark s2"></i><i class="spark s3"></i><i class="spark s4"></i><i class="spark s5"></i>
</section></main>
<script>
const I={
en:{kicker:"Philips pairing",readyTitle:"Connect your Philips TV",readySub:"Your phone is only used during this one-time pairing.",s1:"Start pairing",s1h:"Your Philips TV will immediately display a PIN.",s2:"Keep the PIN window open on the TV",s2h:"Do not press Close on the Philips screen.",s3:"Enter the PIN on this phone",s3h:"AmbiGovee sends it directly to the TV over your local network.",start:"START PAIRING",waitingTitle:"Enter the PIN shown on your TV",waitingSub:"Keep the Philips PIN window open while you type the code here.",connect:"CONNECT TV",retry:"TRY AGAIN",timer:"Code valid for about {n} s",startingTitle:"Opening pairing on the TV…",startingSub:"The Philips PIN window should appear in a moment.",verifyingTitle:"Connecting your TV…",verifyingSub:"AmbiGovee is validating the PIN locally.",successTitle:"TV connected!",successBody:"Nice — your Philips TV is now paired with AmbiGovee. You can put your phone down and continue on the TV to add your Govee lights.",expiredTitle:"The PIN expired",expiredSub:"No problem. Start again to get a fresh Philips PIN.",errorTitle:"Pairing failed",errorSub:"Try again with a new PIN. Keep the Philips PIN window open on the TV.",readyStatus:"Ready when you are.",waitingStatus:"Waiting for the Philips PIN.",verifyingStatus:"Checking the PIN…",expiredStatus:"The PIN expired.",errorStatus:"The TV did not accept the pairing.",networkError:"Local connection interrupted. Make sure the phone and TV are on the same network.",invalidPin:"Enter the complete PIN shown by Philips.",privacy:"Local connection only • no TV image or Philips pairing credential is sent to an Internet service."},
fr:{kicker:"Association Philips",readyTitle:"Connecte ta TV Philips",readySub:"Ton téléphone sert uniquement pendant cette première association.",s1:"Démarre l'association",s1h:"La TV Philips affichera immédiatement un PIN.",s2:"Laisse la fenêtre du PIN ouverte sur la TV",s2h:"N'appuie surtout pas sur Fermer côté Philips.",s3:"Entre le PIN sur ce téléphone",s3h:"AmbiGovee l'envoie directement à la TV sur ton réseau local.",start:"DÉMARRER L'ASSOCIATION",waitingTitle:"Entre le PIN affiché sur ta TV",waitingSub:"Garde la fenêtre du PIN Philips ouverte pendant que tu tapes le code ici.",connect:"CONNECTER LA TV",retry:"RECOMMENCER",timer:"Code valable encore environ {n} s",startingTitle:"Ouverture de l'association sur la TV…",startingSub:"La fenêtre du PIN Philips devrait apparaître dans un instant.",verifyingTitle:"Connexion de ta TV…",verifyingSub:"AmbiGovee valide le PIN localement.",successTitle:"TV connectée !",successBody:"Parfait — ta TV Philips est maintenant associée à AmbiGovee. Tu peux reposer ton téléphone et continuer sur la TV pour ajouter tes lumières Govee.",expiredTitle:"Le PIN a expiré",expiredSub:"Pas grave. Recommence pour obtenir un nouveau PIN Philips.",errorTitle:"Association impossible",errorSub:"Réessaie avec un nouveau PIN en gardant la fenêtre Philips ouverte sur la TV.",readyStatus:"Prêt quand tu veux.",waitingStatus:"En attente du PIN Philips.",verifyingStatus:"Vérification du PIN…",expiredStatus:"Le PIN a expiré.",errorStatus:"La TV n'a pas accepté l'association.",networkError:"Connexion locale interrompue. Vérifie que le téléphone et la TV sont sur le même réseau.",invalidPin:"Entre le PIN complet affiché par Philips.",privacy:"Connexion locale uniquement • aucune image de la TV ni identifiant d'association Philips n'est envoyé vers un service Internet."}};
let lang=(localStorage.getItem("ambigoveePairLang")||((navigator.language||"en").toLowerCase().startsWith("fr")?"fr":"en"));const $=s=>document.querySelector(s);let current={state:"ready"};function t(k){return(I[lang]&&I[lang][k])||I.en[k]||k}
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));$("#enBtn").classList.toggle("active",lang==="en");$("#frBtn").classList.toggle("active",lang==="fr");render(current)}
$("#enBtn").onclick=()=>{lang="en";localStorage.setItem("ambigoveePairLang",lang);applyLang()};$("#frBtn").onclick=()=>{lang="fr";localStorage.setItem("ambigoveePairLang",lang);applyLang()};
const base=location.pathname.replace(/\\/$/,"");async function call(path,opt){const r=await fetch(base+path,Object.assign({cache:"no-store"},opt||{}));return await r.json()}function busy(v){$("#start").disabled=v;$("#send").disabled=v;$("#retry").disabled=v}
function render(s){current=s||{state:"ready"};busy(false);const intro=$("#intro"),form=$("#pinForm"),retry=$("#retry"),status=$("#status"),success=$("#success"),flow=$("#flow"),title=$("#title"),sub=$("#subtitle"),timer=$("#timer");intro.classList.add("hidden");form.classList.remove("show");retry.classList.add("hidden");success.classList.remove("show");flow.classList.remove("hidden");status.className="status";timer.textContent="";if(current.state==="ready"){intro.classList.remove("hidden");title.textContent=t("readyTitle");sub.textContent=t("readySub");status.textContent=t("readyStatus")}else if(current.state==="starting"){title.textContent=t("startingTitle");sub.textContent=t("startingSub");status.textContent=t("startingSub");busy(true)}else if(current.state==="waiting_pin"){form.classList.add("show");title.textContent=t("waitingTitle");sub.textContent=t("waitingSub");status.textContent=t("waitingStatus");timer.textContent=current.seconds_left>0?t("timer").replace("{n}",current.seconds_left):"";if(document.activeElement!==$("#pin"))$("#pin").focus()}else if(current.state==="verifying"){form.classList.add("show");title.textContent=t("verifyingTitle");sub.textContent=t("verifyingSub");status.textContent=t("verifyingStatus");busy(true)}else if(current.state==="success"||current.paired){flow.classList.add("hidden");success.classList.add("show")}else if(current.state==="expired"){retry.classList.remove("hidden");title.textContent=t("expiredTitle");sub.textContent=t("expiredSub");status.textContent=t("expiredStatus");status.classList.add("warn")}else{retry.classList.remove("hidden");title.textContent=t("errorTitle");sub.textContent=t("errorSub");status.textContent=t("errorStatus");status.classList.add("bad")}}
$("#start").onclick=async()=>{busy(true);try{render(await call("/start",{method:"POST"}))}catch(e){$("#status").textContent=t("networkError");$("#status").className="status bad";busy(false)}};$("#retry").onclick=async()=>{busy(true);$("#pin").value="";try{render(await call("/start",{method:"POST"}))}catch(e){busy(false)}};$("#pinForm").onsubmit=async e=>{e.preventDefault();const v=$("#pin").value.trim();if(!/^\\d{4,8}$/.test(v)){$("#status").textContent=t("invalidPin");$("#status").className="status warn";return}busy(true);try{render(await call("/pin",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:"pin="+encodeURIComponent(v)}))}catch(e){$("#status").textContent=t("networkError");$("#status").className="status bad";busy(false)}};async function poll(){try{render(await call("/status"))}catch(e){}setTimeout(poll,700)}applyLang();poll();
</script>
</body>
</html>
""";
    }
}
