Tu crées le tag v1.6.1
        ↓
GitHub compile l'APK RELEASE
        ↓
signe l'APK
        ↓
crée la Release
        ↓
ajoute :
AmbiGoveeTV.apk
AmbiGoveeTV-Windows.zip
        ↓
ta TV détecte la Release
        ↓
télécharge AmbiGoveeTV.apk
        ↓
mise à jour
